### ISSUE TITLE
Can I use prepareSpec without @AutoScan?

### ISSUE THREAD

**Issue by dondod** [kotest/kotest#3979] opened 2024-04-23 19:09 UTC
I currently use an approach like the following to set up a database schema before tests run.  It needs to happen before any test class is loaded. 

```kotlin
class KotestExtensions {
    @AutoScan
    class PrepareSpecTestListener : TestListener {
        override suspend fun prepareSpec(kclass: KClass<out Spec>) {
            // set up database, etc.
        }
    }
}
```

But this generates this warning: 
```
Warning: Kotest autoscan is enabled. This means Kotest will scan the classpath for extensions that are annotated with @AutoScan.
 To avoid this startup cost, set autoscan to false by setting the system property 'kotest.framework.classpath.scanning.config.disable=true'. In 6.0 this value will default to true. For further details see 
https://kotest.io/docs/next/framework/project-config.html#runtime-detection
```

I've tried disabling `autoscan` in another project that doesn't need the database setup, and it speeds up the test startup by several seconds (maybe 5 or more).

Is there a way to use `prepareSpec` without using `@AutoScan`?

**Comment by Kantis** [comment] 2024-04-23 21:18
You can define `kotest.properties` (details [here](https://kotest.io/docs/intellij/intellij-properties.html)) with the following content:
```
kotest.framework.classpath.scanning.config.disable=true
kotest.framework.classpath.scanning.autoscan.disable=true
kotest.framework.config.fqn=com.myproject.KotestConfig
```

Where `com.myproject.KotestConfig` is
```kotlin
object KotestConfig : AbstractProjectConfig() {
  override fun extensions() = listOf(
    PrepareSpecTestListener()
  )
}
```

That should get rid of runtime detection while also letting you configure Kotest.

**Comment by dondod** [comment] 2024-04-23 21:40
Thanks!  That almost worked.. I get an error though: 
```
io.kotest.engine.spec.SpecInstantiationException: Could not create instance of class com.myproject.MySpec. Specs must have a public zero-arg constructor.
	at io.kotest.engine.spec.InstantiateSpecKt.javaReflectNewInstance(instantiateSpec.kt:46)
	at io.kotest.engine.spec.InstantiateSpecKt.createAndInitializeSpec(instantiateSpec.kt:30)
	at io.kotest.engine.spec.InstantiateSpecKt.instantiate(instantiateSpec.kt:11)
	at io.kotest.engine.spec.SpecRefKt.instance(SpecRef.kt:14)
	at io.kotest.engine.spec.SpecExecutor.createInstance-gIAlu-s(SpecExecutor.kt:63)
	at io.kotest.engine.spec.SpecExecutor.access$createInstance-gIAlu-s(SpecExecutor.kt:24)
	at io.kotest.engine.spec.SpecExecutor$execute$innerExecute$1.invokeSuspend(SpecExecutor.kt:40)
...
```

Would that be because I pass a mock into the spec constructor?  e.g., 
```kotlin
class MySpec(@MockkBean private val foo: Foo) : DescribeSpec({
    //
})
```

**Comment by dondod** [comment] 2024-04-26 17:00
Moving the parameters out of the `MySpec` constructor works, but then I need to use `init {...` and change the way all the passed-in (usually auto-wired) arguments are dealt with.  This is a common pattern with Spring Boot (for better or worse), so I wonder if there's a way allow passing arguments to the spec constructors.

**Comment by Kantis** [comment] 2024-05-08 18:47
@dondod sorry for taking so long.. It's because the [SpringAutowireConstructorExtensions](https://github.com/kotest/kotest-extensions-spring/blob/master/src/main/kotlin/io/kotest/extensions/spring/SpringAutowireConstructorExtension.kt) from kotest-extensions-spring relies on `@AutoScan` to be discovered. When you disable scanning, you need to also register this extension manually from your `KotestConfig`. 

You probably also want to register the [SpringExtension](https://github.com/kotest/kotest-extensions-spring/blob/master/src/main/kotlin/io/kotest/extensions/spring/SpringTestExtension.kt#L48)

**Comment by dondod** [comment] 2024-05-08 22:54
Thanks @Kantis! This works well in many cases for me (reducing test startup time by 7-8 seconds), but now the mocks declared by `@MockkBean` only work once.  I'll see if I can narrow down the cause.

**Comment by Kantis** [comment] 2024-05-09 07:09
Feel free to post a small example repo 🙂

**Comment by dondod** [comment] 2024-05-09 23:56
Thanks, I'll try that soon..

**Comment by dondod** [comment] 2024-05-10 16:26
Hi @Kantis - I was able to reproduce this in a small demo app here: https://github.com/dondod/kotest-mockk-springboot-demo/blob/main/src/test/kotlin/com/example/demo/WidgetServiceSpec.kt 

When both tests are run, the second one fails with:
```
no answer found for WidgetDb(com.example.demo.WidgetDb#0 bean#1).getWidgets() among the configured answers: ()
```

The tests pass if I put the mock setup inside a `beforeEach`, but I'm not using `beforeEach` in my real project in some places.

**Comment by dondod** [comment] 2024-05-24 20:59
Hi @Kantis - I tried looking into this further but I just don't get how this works.

**Comment by dondod** [comment] 2024-07-03 19:32
It turns out that removing the `SpringExtension` from the list of extensions fixed the problem.

**Comment by Kantis** [comment] 2024-07-04 06:42
MockkBean seems to rely on the Spring Test lifecycle (see [here](https://github.com/Ninja-Squad/springmockk/blob/master/src/main/kotlin/com/ninjasquad/springmockk/ClearMocksTestExecutionListener.kt)) to reset mocks between each test, so I would say this is expected behaviour. 

To setup the mocks once for both tests you could use the Kotest lifecycle hook `beforeEach`

```kotlin
@ContextConfiguration(
    classes = [WidgetService::class]
)
class WidgetServiceSpec(
    private val widgetService: WidgetService,
    @MockkBean private val widgetDb: WidgetDb
) : DescribeSpec({
    describe("getWidgets") {
        beforeEach { // <-- Change here
           every { widgetDb.getWidgets() } returns listOf(Widget(5), Widget(6))
        }

        it("returns the mocked widgets") {
            val widgets = widgetService.getWidgets()
            widgets.shouldBe(listOf(Widget(5), Widget(6)))
        }

        it("still returns the mocked widgets") {
            val widgets = widgetService.getWidgets()
            widgets.shouldBe(listOf(Widget(5), Widget(6)))
        }
    }
})
```

**Comment by dondod** [comment] 2024-07-04 20:37
Yeah, the problem is that I'm not using `beforeEach` in all my tests in my real project.  If there was a `before` hook, that would probably work (https://github.com/kotest/kotest/issues/2792).

**Comment by AShynkevich** [comment] 2024-09-09 07:25
Hi I believe my question is related to this topic, since I need to use SpringExtension but I can't do it without "autoscan" feature. 

Even I provided the configuration:
```
kotest.framework.classpath.scanning.config.disable=true
kotest.framework.classpath.scanning.autoscan.disable=true
kotest.framework.config.fqn=com.test.kotest.KotestConfig // here is springExtenstion is registered
```

I got the error:
`"Could not create instance of class com.test.kotest.ServiceTest. Specs must have a public zero-arg constructor."`

If comment the property:
```
kotest.framework.classpath.scanning.config.disable=true
#kotest.framework.classpath.scanning.autoscan.disable=true
kotest.framework.config.fqn=com.test.kotest.KotestConfig // here is springExtenstion is registered
```
it starts working but I have the annoying warning: "Warning: Kotest autoscan is enabled. This means Kotest will scan the classpath for extensions that are annotated with @AutoScan...."

Is there way using  SpringExtension and get rid off the warning? 

[kotest version: 5.9.1]

**Comment by jpalaz** [comment] 2024-10-11 12:33
> Is there way using SpringExtension and get rid off the warning?

Yes! I've checked on my project the solution that guys discussed above, and it worked. https://github.com/kotest/kotest/issues/3979#issuecomment-2101215965

_Works both for kotest 5.9.1 and 6.0.0.M1_

You **don't need to register** `SpringExtension`, but you **need to register** `SpringAutowireConstructorExtension`:

```kotlin
package com.your.package

import io.kotest.core.config.AbstractProjectConfig
import io.kotest.extensions.spring.SpringAutowireConstructorExtension

object KotestConfig : AbstractProjectConfig() {
    override fun extensions() = listOf(SpringAutowireConstructorExtension)
}
```

And now you neither have Autoscan warning, nor an error with zero-arg constructor 🎉  Kudos to @dondod and @Kantis

**Comment by AShynkevich** [comment] 2024-10-17 06:24
Yep, you're right! It works properly. Just need everything make autowiring via ctor.

Thanks a lot!

**Comment by sksamuel** [comment] 2024-12-08 11:19
Closing since this works.

**Closed as completed by sksamuel** 2024-12-08 11:19 UTC
Labels: extensions 🔋
