### ISSUE TITLE
Junit5 test file automatic creation error when using intellij kotest

### ISSUE THREAD

**Issue by connor-27** [kotest/kotest#3709] opened 2023-09-26 01:57 UTC
----
Kotest version: 5.5.5
Kotest Plugin version : 4.1.0
Intellij version : 2023.2.2

----

It's exactly as the title says.
To use Kotest, I installed the kotest plugin in Intellij.

When using the "Create New Test" -> automatic test class file creation function provided by Intellij,
If you select Junit rather than Kotest, no Test file will be created.

Since some team members in charge of the project are not familiar with Kotest, they are trying to use Juinit and Kotest together, but it is difficult to guide them due to the above issues.

Please check the issue.
Personally, I am very satisfied with kotest because it provides visibility and makes it easy to write separate tests for different purposes.

thank you

**Comment by herveDarritchon** [comment] 2023-10-04 08:24
I also experience the same issue so I had to remove the Kotest plugin :( That's a shame.
Very annoying !

**Comment by LeoColman** [comment] 2023-10-06 15:52
Duplicate of https://github.com/kotest/kotest/issues/3689

**Closed as completed by LeoColman** 2023-10-06 15:52 UTC
Labels: intellij-plugin 🖥️
