### ISSUE TITLE
Can't create a test class neither in Java nor Kotlin with Kotest Plugin enabled

### ISSUE THREAD

**Issue by ostfale** [kotest/kotest#3692] opened 2023-09-15 06:15 UTC
Intellij Youtrack : https://youtrack.jetbrains.com/issue/KTIJ-26857

IntelliJ IDEA 2023.2.2 (Ultimate Edition)
Build #IU-232.9921.47, built on September 12, 2023

Runtime version: 17.0.8+7-b1000.22 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0

Non-Bundled Plugins:
    org.nik.presentation-assistant (1.0.10)
    com.github.copilot (1.2.22.3129)
    org.jetbrains.plugins.go-template (232.8660.88)
    AceJump (3.8.15)
    com.intellij.kubernetes (232.9921.28)
    com.intellij.spring.shell (232.8660.142)
    com.intellij.spring.websocket (232.8660.142)
    com.intellij.bigdatatools.core (232.9921.47)
    com.intellij.bigdatatools.kafka (232.9921.47)
    MavenRunHelper (4.25.1-IJ2022.2)
    org.asciidoctor.intellij.asciidoc (0.38.20)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-232)
    izhangzhihao.rainbow.brackets (2023.3.4)
    kotest-plugin-intellij (1.3.69-IC-232-EAP-SNAPSHOT)

Kotlin: 232-1.9.0-IJ9921.47

**Comment by sksamuel** [comment] 2023-09-17 16:03
Closing as duplicate of #3689
Will add comments in that other ticket.

**Closed as completed by sksamuel** 2023-09-17 16:03 UTC
