### ISSUE TITLE
kotest-runner-junit5-jvm:4.1.3 does not respect Gradle's "--tests" filter

### ISSUE THREAD

**Issue by stefanneuhaus** [kotest/kotest#1622] opened 2020-08-11 08:48 UTC
In a mixed Kotlin/Java test source set when using Gradle's `--tests` filter to selectively execute some non-Kotlin tests, all Kotlin tests get executed as well.

I provided a basic test project that reproduces the issue: [stefanneuhaus/kotest-issue](https://github.com/stefanneuhaus/kotest-issue)

- The issue does not occur with version 4.1.2.
- I did not yet test the junit4 runner.

**Comment by sksamuel** [comment] 2020-08-11 13:57
Duplicate of #1531
Will be fixed for 4.2.0, due very soon!

**Comment by sksamuel** [comment] 2020-08-13 23:07
There is a fix included in 4.2.0.RC2 if you want to try that.
4.2.0 final will follow shortly.
@stefanneuhaus

**Comment by stefanneuhaus** [comment] 2020-08-14 06:14
@sksamuel Thank you for the timely reaction. I tried to verify the fix in 4.2.0.RC2 with [stefanneuhaus/kotest-issue](https://github.com/stefanneuhaus/kotest-issue) but failed. Seems like either the bug is not yet fixed or it is no duplicate of #1531.

**Comment by rd-stefan-neuhaus** [comment] 2020-08-20 15:16
I tested with the release version 4.2.0: It is actually fixed.

And I double-checked that it is failing with 4.2.0.RC2. Anyway, seems to be fixed -- works for me. :-)

**Closed as completed** 2020-08-23 17:38 UTC
Labels: framework 🏗️
