### ISSUE TITLE
Js tests are allways passing 

### ISSUE THREAD

**Issue by JimeFuture** [kotest/kotest#2382] opened 2021-07-23 13:26 UTC
Im in a mulitplatform project. Setup was done like discibed in the "get started" section.
The jvmTests are working as aspected.

The jsTests are always passing, even it not could pass at all:
```
class Main : FunSpec({
                         test("File") {
                             2 shouldBeGreaterThan 15
                         }
                     })
```
Is there any additional setup must be done?

**Comment by sksamuel** [comment] 2021-07-23 13:28
IR mode ?

**Comment by JimeFuture** [comment] 2021-07-23 13:30
Yes jvm and js complier both set to IR

**Comment by ashishkujoy** [comment] 2021-07-28 13:57
This is getting track here: #2163

**Comment by sksamuel** [comment] 2021-08-01 16:38
Yep duplicate of https://github.com/kotest/kotest/issues/2163

**Closed as completed by sksamuel** 2021-08-01 16:38 UTC
