### ISSUE TITLE
AnnotationSpec: Exception in project-level `TestListener`'s `beforeSpec` causes all test cases to be silently not run

### ISSUE THREAD

**Issue by andrey-bolduzev** [kotest/kotest#1426] opened 2020-04-30 15:23 UTC
I have a project that uses Mockito for mocking. The project config looks something like this:

```kotlin
object KotestConfig : AbstractProjectConfig() {

	override val isolationMode: IsolationMode? = InstancePerLeaf

	override fun listeners(): List<TestListener> = listOf(MockitoInjectListener)
}

private object MockitoInjectListener : TestListener {

	override suspend fun beforeSpec(spec: Spec) {
		MockitoAnnotations.initMocks(spec)
	}
}
```

The situation is as follows:
1. I'm writing a new `AnnotationSpec` test, utilizing `@Mock` and `@InjectMock` to provide dependencies I need.
2. But I forget to `@Mock`-inject something and Mockito cannot construct the `@InjectMock`-annotated object and throws `InjectMocksException` from the `initMocks()`.
3. From what I can see this makes the chain in `InstancePerLeafSpecRunner#executeInCleanSpec` fall through without executing the test cases but also without reporting its failure to do so. So when running all tests in the project, the developer assumes that everything is passing.

**Comment by sksamuel** [comment] 2020-04-30 17:31
Which version ?

**Comment by andrey-bolduzev** [comment] 2020-04-30 17:34
> Which version ?

My bad, 4.0.2.

**Comment by sksamuel** [comment] 2020-04-30 17:51
Thanks, can you try 4.0.5 as a related bug was fixed. If it still doesn't
work I'll investigate.

**Comment by andrey-bolduzev** [comment] 2020-04-30 20:31
> Thanks, can you try 4.0.5 as a related bug was fixed. If it still doesn't work I'll investigate.

Tried with 4.0.5. Still the same silent failure, I'm afraid.

**Comment by sksamuel** [comment] 2020-04-30 22:14
Alright thanks, we'll look into it.

**Comment by ashishkujoy** [comment] 2020-05-13 05:38
@andrey-bolduzev could you please provide us a sample project which reproduce this bug.
I have tried doing that, for me its working fine, i am getting the expected exception even before my spec run.

Here is the project config where i am adding a listener which throws InjectMocksException in beforeSpec callback
https://github.com/ashishkujoy/kotest-playground/blob/issue-1426/src/test/kotlin/com/kotest/playground/ProjectConfig.kt

Here is the annotation spec style based test
https://github.com/ashishkujoy/kotest-playground/blob/issue-1426/src/test/kotlin/com/kotest/playground/AFailingTest.kt

On running test i get the desired exception

**Comment by andrey-bolduzev** [comment] 2020-05-13 14:52
> @andrey-bolduzev could you please provide us a sample project which reproduce this bug.
> I have tried doing that, for me its working fine, i am getting the expected exception even before my spec run.

Thank you very much for providing the sample project.

One thing I changed in it is adding a `override val isolationMode: IsolationMode = IsolationMode.InstancePerLeaf` line to the `ProjectConfig` and it started silently failing like in the original report. So, might be, there's a bug only in the `InstancePerLeafSpecRunner` but not the rest of them?

**Comment by ashishkujoy** [comment] 2020-05-13 16:00
Oh yes,  with ```InstancePerLeaf```  i am also not seeing the error.

**Comment by ashishkujoy** [comment] 2020-05-16 03:45
@andrey-bolduzev The bug is now fixed in master.

**Closed as completed by ashishkujoy** 2020-05-16 03:45 UTC
Labels: framework 🏗️

**Comment by andrey-bolduzev** [comment] 2020-06-02 02:04
The fix works wonderfully in the kotest snapshot version but I was wondering if it would be possible to cherry-pick it into a stable 4.0 release?

I'm currently torn between having to use 4.0 which has the dangerous bug and 4.1 which has it fixed but which at the same time has a new issue that prevents the android studio / Intellij from recognizing test cases which makes them not runnable from the IDE.

**Comment by sksamuel** [comment] 2020-06-02 02:25
What's the new bug ?

**Comment by andrey-bolduzev** [comment] 2020-06-02 02:45
> What's the new bug ?

Haven't seen it reported and still trying to figure out what the cause might be. But when switching from kotest 4.0 to 4.1, the IDE stops recognizing kotest specs as valid test files which is manifested by the green "run" button in the gutter section disappearing (as well as any other way to run individual test classes from the IDE except for the command line). This affects at least classes extending the `AnnotationSpec` and the `BehaviorSpec` and happens uniformly in the Android Studio 3.6.3, 4.0, and Intellij 2020.2 EAP, from what I've tried. The android gradle plugin is 4.0 although I'm pretty sure this was happening with the AGP 3.6 as well.

**Comment by sksamuel** [comment] 2020-06-02 03:03
Ah that's expected.

So in <= 4.0 Kotest spec files "pretend" to be JUnit class files by adding the junit annotaton @Testable to the specs. This is so intellij thinks they're junit files and then gives you the green button. But because junit is limited to classes and methods, it only shows you the green button at the top level.

In 4.1 we have removed this annotation. Instead, we will advertise the kotest intellij plugin.
https://github.com/kotest/kotest-intellij-plugin

This is being used by dozens of people now, against the 4.1 snapshot branch. It needs to be installed manually, and it's beta (but I think basically final).

The benefits are you have a green play button at every test level not just the class level. In addition you have the kotest tool window in intellij, and other goodies. See the plugin readme.

The downside is that unless you install the plugin you don't get any green button at all. 

I think it's a good tradeoff, the plugin is better, open source and stable. Why wouldn't you want to install it? Plus in the future, I hope that jetbrains include it in the intellij distribution as they do for scalatest and other frameworks.

Thoughts?

**Comment by sksamuel** [comment] 2020-06-02 03:05
We should still include this fix in 4.0.x though. I'll release 4.0.7 with this next few days.

**Comment by sksamuel** [comment] 2020-06-02 03:06
@ashishkujoy you think you can raise a PR against release/4.0.x branch with the fix, I notice the original fix was several commits and might be hard to cherry-pick.

**Comment by ashishkujoy** [comment] 2020-06-02 03:16
Sure @sksamuel

**Comment by andrey-bolduzev** [comment] 2020-06-02 03:30
> Ah that's expected.

The only reason I haven't gotten to installing the plugin yet is I wasn't sure of the state of its compatibility with kotest 4.0, but I've been meaning to try it out and I will certainly do it now. Thank you very much for your work @sksamuel @ashishkujoy.

**Comment by sksamuel** [comment] 2020-06-02 03:46
Thank you for using the project and your feedback.

**Comment by andrey-bolduzev** [comment] 2020-06-16 17:46
Don't mean to interfere with the release process but if I'm not mistaken that fix got cherry-picked but never released? Would it still be possible to still make a small 4.0.7 stable release? @sksamuel @ashishkujoy

**Comment by ashishkujoy** [comment] 2020-06-17 02:36
Hi @andrey-bolduzev That fix was released 4.1.0-RC1 few days back. You can use latest 4.1.0-RC2.

**Comment by andrey-bolduzev** [comment] 2020-06-17 03:36
> Hi @andrey-bolduzev That fix was released 4.1.0-RC1 few days back. You can use latest 4.1.0-RC2.

Yep, I know it's fixed in the 4.1 branch but the adoption of the kotest intellij plugin is not going too well in my team, I am having a hard time getting it to work in a complex project myself. I was going to raise an issue in the plugin repo once I figure out what exactly is happening. But in the meantime, I was hoping another small 4.0 release could be made since the work to cherry-pick the change was done already anyway if I'm not mistaken.

**Comment by sksamuel** [comment] 2020-06-17 03:54
We can do 4.0.7 yes.

Also please let us know what issues you're having with the plugin and 4.1.

**Comment by sksamuel** [comment] 2020-06-20 14:13
4.0.7 has been released.
