### ISSUE TITLE
Multiplatform - only one common test gets executed on JS and time reporting for JVM tests doesn't work

### ISSUE THREAD

**Issue by JoonasC** [kotest/kotest#2682] opened 2021-11-28 13:38 UTC
**Which version of Kotest are you using**
5.0.0

I have 4 common tests: SyntaxCheckerTests, TokenizerTests, ConnectionTests and ObjectCreationUtilsTests, for some reason with a multiplatform setup similar to [https://github.com/kotest/kotest-examples-multiplatform](https://github.com/kotest/kotest-examples-multiplatform) only the ConnectionTests test gets run on browser JS and all the other tests get ignored.

All of the tests are StringSpec tests, so I don't see why the others get ignored.

Also, time reporting doesn't work properly for JVM tests:
![image](https://user-images.githubusercontent.com/3898724/143770082-3ec189c6-f297-4118-8552-75762cb15835.png)
All the tests in SyntaxCheckerTests take at least 500ms each, yet IDEA reports 0 ms for them.

**Comment by sksamuel** [comment] 2021-11-28 14:21
Do you have node target?

**Comment by JoonasC** [comment] 2021-11-28 14:22
@sksamuel Nope only the browser target

**Comment by JoonasC** [comment] 2021-11-28 14:24
Also, I was thinking this might have something to do with the fact that all of my common tests are not in the same subdirectory within the common tests directory..

**Comment by sksamuel** [comment] 2021-11-28 14:26
Different packages you mean?

**Comment by JoonasC** [comment] 2021-11-28 14:26
Yeah, as you can see on the attached screenshot for the running JVM test.

**Comment by sksamuel** [comment] 2021-11-28 14:29
Shouldn't matter.

Can you remove js and or jvm targets, see if native appears.

**Comment by JoonasC** [comment] 2021-11-28 14:31
I don't have a native target, because I don't need it.

**Comment by JoonasC** [comment] 2021-11-28 14:31
It's only JVM (with Java support), and browser JS.

**Comment by sksamuel** [comment] 2021-11-28 14:45
I'm guessing you can't share the project because of privacy reasons?

**Comment by JoonasC** [comment] 2021-11-28 14:46
Yeah, but I can put together a reproducer, if it would help

**Comment by sksamuel** [comment] 2021-11-28 14:48
Yes definitely.
I've just tried different packages and it works for me.

**Comment by sksamuel** [comment] 2021-11-28 15:58
I've updated the examples project with multiple package tests and it still works.
I've also bumped all the versions to 5.0.0 final. Are you using 5.0.0 or the snapshot version that was in the repo ?

**Comment by JoonasC** [comment] 2021-11-28 16:04
The final 5.0.0 version, I'll try to have a reproducer ready for next week

**Comment by JoonasC** [comment] 2021-11-28 21:03
@sksamuel The following reproduces the issue for me: [kotest-repro.zip](https://github.com/kotest/kotest/files/7614359/kotest-repro.zip)
![image](https://user-images.githubusercontent.com/3898724/143785806-c6737bcb-0be4-43d5-9870-5f9f42770132.png)

**Comment by sksamuel** [comment] 2021-11-28 21:18
![image](https://user-images.githubusercontent.com/743706/143786360-85a2d83b-b42f-4227-9e15-b2ebdb04b8cb.png)

**Comment by JoonasC** [comment] 2021-11-28 21:21
Yes, that seems like the same behavior. As you can see only the Bar test got executed with browser JS, and the t2 test for Foo reports 0ms even though I put a 2000ms delay in that test.

**Comment by sksamuel** [comment] 2021-11-28 21:26
Yeah, I can see the tests are being generated by the compiler plugin, so trying to figure out why they're not being picked up at runtime.

**Comment by sksamuel** [comment] 2021-11-28 22:13
Looks like it is this: https://github.com/kotest/kotest/issues/2683. I thought that issue was node only but seems its not.

**Comment by JoonasC** [comment] 2021-11-28 22:18
Ok, what about the incorrect time reporting? That's not a JS issue

**Comment by sksamuel** [comment] 2021-11-28 22:19
In the JVM it's a known regression and will be fixed in 5.0.1.

**Comment by sksamuel** [comment] 2021-11-28 22:20
https://github.com/kotest/kotest/issues/2686

**Comment by JoonasC** [comment] 2021-11-28 22:20
👍

**Comment by sksamuel** [comment] 2021-11-28 22:22
If you can upvote this issue, it might help: https://youtrack.jetbrains.com/issue/KT-49851

**Comment by JoonasC** [comment] 2021-11-28 22:23
Done

**Comment by sksamuel** [comment] 2021-11-28 22:36
Catching the error seems to make it work, as the exception seems to happen when the final coroutine context is being released, which at that point, your test is completed anyway. So I've got it working in a local build and I guess is a workaround until Jetbrains fix it properly.

There seems to be another issue with a race condition that I'm looking at, where sometimes not all the specs are detected by the compiler plugin. This seems unrelated and might be solved by simply using thread safe collections in the plugin.

**Comment by sksamuel** [comment] 2021-11-28 22:42
https://github.com/kotest/kotest/pull/2688

**Comment by JoonasC** [comment] 2021-11-29 15:48
Also a minor QOL issue, but it seems like with Kotest 5.0.0 IDEA doesn't show the currently running test anymore. As you can see with the first screenshot, only completed tests in a spec are shown but not the currently running test.

**Comment by sksamuel** [comment] 2021-11-29 16:26
It's related to the timing issue in Junit. May be changed for 5.0.1 or more
likely 5.0.2

**Comment by JoonasC** [comment] 2021-11-29 17:34
Any ETA on 5.0.1 or 5.0.2?

**Comment by sksamuel** [comment] 2021-11-29 17:54
Today for 5.0.1

**Comment by JoonasC** [comment] 2021-11-30 13:36
@sksamuel Not sure if this is also a bug but I'm getting this when running tests that take a lot of time on JS:
```
> Task :jsBrowserTest
Disconnected (0 times) reconnect failed before timeout of 2000ms (ping timeout)
java.lang.IllegalStateException: command '/home/joonas/.gradle/nodejs/node-v14.17.0-linux-x64/bin/node' exited with errors (exit code: 1)
```

I could just try to increase the timeout, but I think I shouldn't have to make the timeout as long as the total runtime of all my tests?

It's most likely this: [https://karma-runner.github.io/5.0/config/configuration-file.html#browserdisconnecttimeout](https://karma-runner.github.io/5.0/config/configuration-file.html#browserdisconnecttimeout)

**Comment by JoonasC** [comment] 2021-11-30 13:46
This might also be related: [https://discuss.kotlinlang.org/t/configuring-timeouts-when-running-mocha-based-tests-in-mpp-or-js-projects/16567](https://discuss.kotlinlang.org/t/configuring-timeouts-when-running-mocha-based-tests-in-mpp-or-js-projects/16567)

**Comment by JoonasC** [comment] 2021-11-30 16:26
Maybe I should move the new question into a new issue, since this issue has esssentially been addressed?

**Comment by sksamuel** [comment] 2021-11-30 16:37
Yes please

**Closed as completed** 2021-11-30 16:40 UTC
