### ISSUE TITLE
Wrong error thrown when test exceeds invocation time out

### ISSUE THREAD

**Issue by KeremAslan** [kotest/kotest#1807] opened 2020-10-27 08:42 UTC
**Which version of Kotest are you using**
1.4.10

I have noticed that if a test exceeds its `invocationTimeout` kotest throws a `TimeoutException`. 
In my case I am running 3 parametrized tests that have configured as follows:

```
"mytest".config(invocationTimeout = 45.minutes, timeout = 3.hours)
```

This is (part of) the error thrown after roughly 45 minutes:

```
Test did not complete within 10800000ms
TimeoutException(duration=10800000)
    at io.kotest.core.internal.TestCaseExecutor.executeAndWait(TestCaseExecutor.kt:216)
    at io.kotest.core.internal.TestCaseExecutor.invokeTestCase(TestCaseExecutor.kt:161)
    at io.kotest.core.internal.TestCaseExecutor.executeActiveTest(TestCaseExecutor.kt:130)
    at io.kotest.core.internal.TestCaseExecutor$intercept$2.invokeSuspend(TestCaseExecutor.kt:80)
    at io.kotest.core.internal.TestCaseExecutor$intercept$2.invoke(TestCaseExecutor.kt)
    at io.kotest.core.internal.TestCaseExecutor.executeIfActive(TestCaseExecutor.kt:94)
    at io.kotest.core.internal.TestCaseExecutor.intercept(TestCaseExecutor.kt:80)
    at io.kotest.core.internal.TestCaseExecutor.execute(TestCaseExecutor.kt:61)
    at io.kotest.engine.runners.SingleInstanceSpecRunner.runTest(SingleInstanceSpecRunner.kt:73)
    at io.kotest.engine.runners.SingleInstanceSpecRunner$Context.registerTestCase(SingleInstanceSpecRunner.kt:51)
    at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3$1$contextp$1.registerTestCase(TestCaseExecutor.kt:204)
    at io.kotest.core.test.TestContext$DefaultImpls.registerTestCase(TestContext.kt:39)
    at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3$1$contextp$1.registerTestCase(TestCaseExecutor.kt:202)
    at io.kotest.core.spec.style.scopes.TestWithConfigBuilder.config-i5u-HFk(TestWithConfigBuilder.kt:49)
    at io.kotest.core.spec.style.scopes.FreeScope.config-FgC7SQg(FreeScope.kt:55)
    at io.kotest.core.spec.style.scopes.FreeScope.config-FgC7SQg$default(FreeScope.kt:48)
```

Shouldn't this be an `InvocationTimeoutException` instead? 

While on that note, may I suggest renaming `invocationTimeout` and `timeout` something more descriptive, e.g  `testCaseTimeout` and `testSuiteTimeout`? Both `timeout` and `invocationTimeout` are very generic a term and it is easy to get confused which one is what.

**Comment by sksamuel** [comment] 2020-10-27 11:19
It doesn't look like you're using invocations in your tests.

**Comment by Woodz** [comment] 2020-10-28 03:19
I have also encountered this issue on kotest 4.3.0.

Reproduction:
```
@ExperimentalTime
class TimeoutTest : FreeSpec({
    val sleepDuration = 2.seconds
    "test".config(invocationTimeout = 1.seconds, timeout = 5.hours) {
        println("Running test. About to sleep at ${System.currentTimeMillis()} for $sleepDuration")
        Thread.sleep(sleepDuration.toLongMilliseconds())
        println("Finished sleeping and running test at ${System.currentTimeMillis()}")
    }
})
```

Output:
```
Running test. About to sleep at 1603854858506 for 2.00s
Finished sleeping and running test at 1603854860511



Process finished with exit code 255

<TimeoutException>
```

Expected TimeoutException: 
```
Test did not complete within 1000ms
TimeoutException(duration=1000)
<stack trace>
```

Actual TimeoutException (note that the timeout duration displayed is from the `timeout` parameter (5 hours) which has not been hit in this scenario:
```
Test did not complete within 18000000ms
TimeoutException(duration=18000000)
<stack trace>
```

**Comment by Woodz** [comment] 2020-10-28 03:22
I'd also recommend including which timeout was hit in the error message to make it very clear, i.e.

```
Single test invocation did not complete within invocation timeout of 1000ms
```

**Comment by KeremAslan** [comment] 2020-10-28 03:32
> It doesn't look like you're using invocations in your tests.

Yes, that's because I want it to run only once. I noticed the default value for `invocations` is `null`, see [here](https://github.com/kotest/kotest/blob/7b5df22b70967123b15e6655ecd57e3252698498/kotest-tests/kotest-tests-timeout/src/test/kotlin/com/sksamuel/kotest/timeout/TimeoutTest.kt). Shouldn't the default value instead be 1? It is an easy mistake to make where someone wants to run the test for longer than the default of 10 mins, and they don't know they need to set the `invocation`.

**Comment by KeremAslan** [comment] 2020-10-28 04:44
I discovered it is because the parent test overrides the timeout values for the leaf tests. So a test like:

```
"Parent test" - { 
    "leaf test".config(timeout=2.hours, invocationTimeout=60.minutes) {
       // my test
   }
}
```
gets overruled by the default time out of its parent test.

**Comment by sksamuel** [comment] 2020-10-29 13:28
> While on that note, may I suggest renaming `invocationTimeout` and `timeout` something more descriptive, e.g `testCaseTimeout` and `testSuiteTimeout`? Both `timeout` and `invocationTimeout` are very generic a term and it is easy to get confused which one is what.

They don't refer to test cases / test suites, they both refer to test cases. Invocation timeout is when you want to run the same test K times, and have a timeout per invocation, and the general timeout is for all invocations of that test (which is usually what people do, ie, 1 invocation).

**Comment by sksamuel** [comment] 2020-10-29 13:30
So ignoring the other bugs (fixed in master now, thanks for the reports), I think this test works as expected:

```kotlin
@ExperimentalTime
class TimeoutTest : FreeSpec({
    val sleepDuration = 2.seconds
    "test".config(invocationTimeout = 1.seconds, timeout = 5.hours) {
        println("Running test. About to sleep at ${System.currentTimeMillis()} for $sleepDuration")
        Thread.sleep(sleepDuration.toLongMilliseconds())
        println("Finished sleeping and running test at ${System.currentTimeMillis()}")
    }
})
```

You're setting a timeout of 1 second for each test invocation and so the test times out after 1 second.
Do you expect different behavior? Can the docs be improved.

**Comment by sksamuel** [comment] 2020-12-22 10:27
I think this is good since 4.3.1. I will close this but please reopen if there is something outstanding.

**Closed as completed by sksamuel** 2020-12-22 10:27 UTC
